# Generated by Django 4.2.2 on 2023-06-23 07:41

from django.db import migrations, models
import django.db.models.deletion
import markdownfield.models
import qtc.models


class Migration(migrations.Migration):

    replaces = [('qtc', '0001_initial'), ('qtc', '0002_alter_question_options_question_question_order'), ('qtc', '0003_quiz_quiz_description_quiz_quiz_description_rendered_and_more'), ('qtc', '0004_rename_response_text_quizentryanswer_answer_text_and_more'), ('qtc', '0005_quiz_file_alter_question_file'), ('qtc', '0006_alter_question_answer_alter_question_file_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('quiz_description', markdownfield.models.MarkdownField(null=True, rendered_field='quiz_description_rendered')),
                ('quiz_description_rendered', markdownfield.models.RenderedMarkdownField(default='')),
                ('file', models.FileField(default='', upload_to=qtc.models.Quiz.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='QuizEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qtc.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IMG', 'Image'), ('AUD', 'Audio'), ('VID', 'Video'), ('TXT', 'Text')], default='IMG', max_length=3)),
                ('file', models.FileField(upload_to=qtc.models.Question.upload_path)),
                ('question_text', models.CharField(blank=True, max_length=200)),
                ('answer', models.CharField(blank=True, max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qtc.quiz')),
                ('question_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['question_order'],
            },
        ),
        migrations.CreateModel(
            name='QuizEntryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=100)),
                ('score', models.FloatField(default=0, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qtc.quizentry')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qtc.question')),
            ],
        ),
    ]
