# Generated by Django 4.2.2 on 2023-06-23 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownfield.models
import qtc.models


class Migration(migrations.Migration):

    dependencies = [
        ('qtc', '0001_squashed_0006_alter_question_answer_alter_question_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(upload_to=qtc.models.Question.upload_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qtc.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.FileField(upload_to=qtc.models.Quiz.upload_path),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_description_rendered',
            field=markdownfield.models.RenderedMarkdownField(),
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='qtc.quiz'),
        ),
        migrations.AlterField(
            model_name='quizentryanswer',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_answers', to='qtc.quizentry'),
        ),
        migrations.AlterField(
            model_name='quizentryanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='qtc.question'),
        ),
    ]
