# Generated by Django 4.2.2 on 2023-06-26 13:53

from django.db import migrations, models
import qtc.models


class Migration(migrations.Migration):

    dependencies = [
        ('qtc', '0007_quizentry_created_at_quizentry_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_url_id',
            field=models.SlugField(default='slug', unique=True, verbose_name='Quiz ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(upload_to=qtc.models.Question.upload_path),
        ),
    ]
