# Generated by Django 4.2.2 on 2023-06-26 17:51

from django.db import migrations, models
import qtc.models


class Migration(migrations.Migration):

    dependencies = [
        ('qtc', '0008_quiz_quiz_url_id_alter_question_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='file',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_media',
            field=models.FileField(null=True, upload_to=qtc.models.Quiz.upload_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(upload_to=qtc.models.Question.upload_path),
        ),
    ]
