# Generated by Django 4.2.2 on 2023-07-28 09:04

from django.db import migrations, models
import qtc.models


class Migration(migrations.Migration):

    dependencies = [
        ('qtc', '0010_alter_question_file_alter_quiz_quiz_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGDBGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('release_date', models.DateField(null=True)),
                ('collection', models.CharField(max_length=500)),
                ('alternate_titles', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(upload_to=qtc.models.Question.upload_path),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_media',
            field=models.FileField(null=True, upload_to=qtc.models.Quiz.upload_path),
        ),
    ]
