# Generated by Django 4.2.2 on 2023-11-06 10:23

from django.db import migrations, models
import qtc.models


class Migration(migrations.Migration):

    dependencies = [
        ('qtc', '0011_igdbgame_alter_question_file_alter_quiz_quiz_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='igdbgame',
            name='ratings_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(upload_to=qtc.models.Question.upload_path),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_media',
            field=models.FileField(null=True, upload_to=qtc.models.Quiz.upload_path),
        ),
    ]
