# Generated by Django 4.2.2 on 2024-09-24 06:27

from django.db import migrations, models
import qtc.models


class Migration(migrations.Migration):

    dependencies = [
        ('qtc', '0012_igdbgame_ratings_count_alter_question_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IGDBGame',
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(upload_to=qtc.models.Question.upload_path),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_media',
            field=models.FileField(null=True, upload_to=qtc.models.Quiz.upload_path),
        ),
    ]
