# Generated by Django 4.2.2 on 2024-09-24 08:51

from django.db import migrations, models
import qtc.models


class Migration(migrations.Migration):

    dependencies = [
        ('qtc', '0013_delete_igdbgame_alter_question_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='squarish_images',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(upload_to=qtc.models.Question.upload_path),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_media',
            field=models.FileField(null=True, upload_to=qtc.models.Quiz.upload_path),
        ),
    ]
