# Generated by Django 4.2.2 on 2024-09-24 12:18

from django.db import migrations
from django.core.files.base import ContentFile
from PIL import Image
import io
import os

def convert_to_webp(apps, schema_editor):
    Quiz = apps.get_model('qtc', 'Quiz')
    Question = apps.get_model('qtc', 'Question')

    def process_image(image_field):
        if image_field and image_field.name.lower().endswith(('.png', '.jpg', '.jpeg', '.gif')):
            with image_field.open('rb') as f:
                img = Image.open(f)
                img = img.convert('RGB')
                output = io.BytesIO()
                img.save(output, format='WEBP', quality=85)
                output.seek(0)
                new_name = os.path.splitext(image_field.name)[0] + '.webp'
                return ContentFile(output.getvalue(), name=new_name)
        return image_field

    for quiz in Quiz.objects.all():
        if quiz.quiz_media:
            quiz.quiz_media = process_image(quiz.quiz_media)
            quiz.save()

    for question in Question.objects.all():
        if question.file:
            question.file = process_image(question.file)
            question.save()

class Migration(migrations.Migration):

    dependencies = [
        ('qtc', '0014_quiz_squarish_images_alter_question_file_and_more'),
    ]

    operations = [
                migrations.RunPython(convert_to_webp),
    ]
